version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./app/:/usr/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://fastapi:user_test@127.0.0.1:5432/fastapi
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi
volumes:
  postgres_data: